services:
  web:
    build: .
    ports: ["8001:8001"]
    env_file: .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/auth_service
      REDIS_URL: redis://redis:6379/1
      SECRET_KEY: change-me
      DEBUG: "False"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
    depends_on: [db, redis]

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_service
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

volumes:
  pgdata:
